<a href="https://colab.research.google.com/github/SnehaNair3/AI-ML-Learning-Journey/blob/main/LSTM_Practicals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text = """Data plays a vital role in our everyday life.
Directly or indirectly, for daily life decisions, we depend on some data, be it choosing a novel to read from a list of books, buying a thing after considering the budget, and so on.
Have you ever imagined searching for something on Google or Yahoo generates a lot of data?
This data is essential to analyze user experiences.
Getting recommendations on various e-commerce websites after buying a product and tracking parcels during delivery are part of Data Analytics which involves analyzing the raw data to make informed decisions.
But this raw data does not help make decisions if it has some redundancy, inconsistency, or inaccuracy.
Therefore, this data needs to be cleaned before considering for analysis."""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
# Initiate the Tokenizer

tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts([text])

In [5]:
len(tokenizer.word_index)

87

In [6]:
for sentence in text.split('\n'):
  print(sentence)

Data plays a vital role in our everyday life.
Directly or indirectly, for daily life decisions, we depend on some data, be it choosing a novel to read from a list of books, buying a thing after considering the budget, and so on.
Have you ever imagined searching for something on Google or Yahoo generates a lot of data?
This data is essential to analyze user experiences.
Getting recommendations on various e-commerce websites after buying a product and tracking parcels during delivery are part of Data Analytics which involves analyzing the raw data to make informed decisions.
But this raw data does not help make decisions if it has some redundancy, inconsistency, or inaccuracy.
Therefore, this data needs to be cleaned before considering for analysis.


In [7]:
for sentence in text.split('\n'):
  print(tokenizer.texts_to_sequences([sentence])[0])

[1, 21, 2, 22, 23, 24, 25, 26, 10]
[27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4, 34, 35, 2, 36, 8, 37, 14, 2, 38, 15, 16, 17, 39, 18, 40, 3]
[41, 42, 43, 44, 45, 6, 46, 3, 47, 5, 48, 49, 2, 50, 8, 1]
[9, 1, 51, 52, 4, 53, 54, 55]
[56, 57, 3, 58, 59, 60, 61, 15, 14, 2, 62, 18, 63, 64, 65, 66, 67, 68, 8, 1, 69, 70, 71, 72, 17, 19, 1, 4, 20, 73, 7]
[74, 9, 19, 1, 75, 76, 77, 20, 7, 78, 13, 79, 11, 80, 81, 5, 82]
[83, 9, 1, 84, 4, 12, 85, 86, 16, 6, 87]


In [8]:
input_sequences=[]

for sentence in text.split('\n'):
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]


  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [9]:
input_sequences

[[1, 21],
 [1, 21, 2],
 [1, 21, 2, 22],
 [1, 21, 2, 22, 23],
 [1, 21, 2, 22, 23, 24],
 [1, 21, 2, 22, 23, 24, 25],
 [1, 21, 2, 22, 23, 24, 25, 26],
 [1, 21, 2, 22, 23, 24, 25, 26, 10],
 [27, 5],
 [27, 5, 28],
 [27, 5, 28, 6],
 [27, 5, 28, 6, 29],
 [27, 5, 28, 6, 29, 10],
 [27, 5, 28, 6, 29, 10, 7],
 [27, 5, 28, 6, 29, 10, 7, 30],
 [27, 5, 28, 6, 29, 10, 7, 30, 31],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4, 34],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4, 34, 35],


In [10]:
max_len=max([len(x) for x in input_sequences])

In [11]:
max_len

34

In [12]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [13]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  1, 21],
       [ 0,  0,  0, ...,  1, 21,  2],
       [ 0,  0,  0, ..., 21,  2, 22],
       ...,
       [ 0,  0,  0, ..., 85, 86, 16],
       [ 0,  0,  0, ..., 86, 16,  6],
       [ 0,  0,  0, ..., 16,  6, 87]], dtype=int32)

In [14]:
X = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [15]:
X

array([[ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  1, 21],
       [ 0,  0,  0, ...,  1, 21,  2],
       ...,
       [ 0,  0,  0, ..., 12, 85, 86],
       [ 0,  0,  0, ..., 85, 86, 16],
       [ 0,  0,  0, ..., 86, 16,  6]], dtype=int32)

In [16]:
y

array([21,  2, 22, 23, 24, 25, 26, 10,  5, 28,  6, 29, 10,  7, 30, 31,  3,
       11,  1, 12, 13, 32,  2, 33,  4, 34, 35,  2, 36,  8, 37, 14,  2, 38,
       15, 16, 17, 39, 18, 40,  3, 42, 43, 44, 45,  6, 46,  3, 47,  5, 48,
       49,  2, 50,  8,  1,  1, 51, 52,  4, 53, 54, 55, 57,  3, 58, 59, 60,
       61, 15, 14,  2, 62, 18, 63, 64, 65, 66, 67, 68,  8,  1, 69, 70, 71,
       72, 17, 19,  1,  4, 20, 73,  7,  9, 19,  1, 75, 76, 77, 20,  7, 78,
       13, 79, 11, 80, 81,  5, 82,  9,  1, 84,  4, 12, 85, 86, 16,  6, 87],
      dtype=int32)

In [17]:
tokenizer.word_index

{'data': 1,
 'a': 2,
 'on': 3,
 'to': 4,
 'or': 5,
 'for': 6,
 'decisions': 7,
 'of': 8,
 'this': 9,
 'life': 10,
 'some': 11,
 'be': 12,
 'it': 13,
 'buying': 14,
 'after': 15,
 'considering': 16,
 'the': 17,
 'and': 18,
 'raw': 19,
 'make': 20,
 'plays': 21,
 'vital': 22,
 'role': 23,
 'in': 24,
 'our': 25,
 'everyday': 26,
 'directly': 27,
 'indirectly': 28,
 'daily': 29,
 'we': 30,
 'depend': 31,
 'choosing': 32,
 'novel': 33,
 'read': 34,
 'from': 35,
 'list': 36,
 'books': 37,
 'thing': 38,
 'budget': 39,
 'so': 40,
 'have': 41,
 'you': 42,
 'ever': 43,
 'imagined': 44,
 'searching': 45,
 'something': 46,
 'google': 47,
 'yahoo': 48,
 'generates': 49,
 'lot': 50,
 'is': 51,
 'essential': 52,
 'analyze': 53,
 'user': 54,
 'experiences': 55,
 'getting': 56,
 'recommendations': 57,
 'various': 58,
 'e': 59,
 'commerce': 60,
 'websites': 61,
 'product': 62,
 'tracking': 63,
 'parcels': 64,
 'during': 65,
 'delivery': 66,
 'are': 67,
 'part': 68,
 'analytics': 69,
 'which': 70,
 'invo

In [18]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=88)

In [19]:
y.shape

(119, 88)

In [20]:
X.shape

(119, 33)

# Model Building

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [26]:
model = Sequential()
model.add(Embedding(88,100,input_length=33))
model.add(LSTM(150))
model.add(Dense(88,activation='softmax'))

In [27]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
X.shape

(119, 33)

In [30]:
y.shape

(119, 88)

In [31]:
model.fit(X,y,epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 62ms/step - accuracy: 0.0000e+00 - loss: 4.4782
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 0.1261 - loss: 4.4592
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0840 - loss: 4.4315
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.0756 - loss: 4.3542
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.0672 - loss: 4.2959
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.0672 - loss: 4.2578
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.0672 - loss: 4.2119
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.0504 - loss: 4.1725
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.0672 - loss: 4.0916
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.0672 - loss: 4.0079
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.0672 - loss: 3.9401
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0672 

**Test the model**

In [32]:
text2 = "Data"

# tokenization
token_text = tokenizer.texts_to_sequences([text2])[0]
# padding
padded_text = pad_sequences([token_text], maxlen=33, padding='pre')
# model prediction
model.predict(padded_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step


array([[1.09574166e-05, 1.87670663e-02, 1.35004083e-02, 9.40946222e-04,
        1.60737371e-03, 7.35481735e-03, 1.97450790e-04, 4.93404805e-05,
        3.04593977e-05, 4.61968407e-02, 5.27353295e-05, 1.74037868e-05,
        1.70101493e-03, 3.92247930e-05, 7.11773246e-05, 7.51063562e-05,
        5.63069421e-04, 1.99050468e-04, 1.89172613e-04, 2.21819598e-02,
        2.19552516e-04, 6.58900082e-01, 7.52463052e-03, 2.25976063e-03,
        6.76793570e-04, 5.80598135e-04, 2.39899979e-04, 7.59667273e-06,
        1.17031531e-03, 1.85001511e-04, 7.37019363e-05, 1.00990634e-04,
        1.17379772e-04, 4.61370255e-05, 6.95599010e-06, 2.52066384e-05,
        5.89344017e-05, 5.79532934e-05, 3.59824044e-05, 9.32623880e-05,
        1.29248103e-04, 1.29681648e-05, 2.90718395e-02, 7.25561893e-03,
        1.18147733e-03, 2.31932703e-04, 1.51814465e-05, 3.24251268e-05,
        1.35959508e-05, 1.12197904e-05, 1.52104520e-04, 1.24771982e-01,
        9.00011975e-03, 5.28723060e-04, 9.58088785e-05, 5.576179

In [33]:
import numpy as np
pos = np.argmax(model.predict(padded_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


In [34]:
tokenizer.word_index

{'data': 1,
 'a': 2,
 'on': 3,
 'to': 4,
 'or': 5,
 'for': 6,
 'decisions': 7,
 'of': 8,
 'this': 9,
 'life': 10,
 'some': 11,
 'be': 12,
 'it': 13,
 'buying': 14,
 'after': 15,
 'considering': 16,
 'the': 17,
 'and': 18,
 'raw': 19,
 'make': 20,
 'plays': 21,
 'vital': 22,
 'role': 23,
 'in': 24,
 'our': 25,
 'everyday': 26,
 'directly': 27,
 'indirectly': 28,
 'daily': 29,
 'we': 30,
 'depend': 31,
 'choosing': 32,
 'novel': 33,
 'read': 34,
 'from': 35,
 'list': 36,
 'books': 37,
 'thing': 38,
 'budget': 39,
 'so': 40,
 'have': 41,
 'you': 42,
 'ever': 43,
 'imagined': 44,
 'searching': 45,
 'something': 46,
 'google': 47,
 'yahoo': 48,
 'generates': 49,
 'lot': 50,
 'is': 51,
 'essential': 52,
 'analyze': 53,
 'user': 54,
 'experiences': 55,
 'getting': 56,
 'recommendations': 57,
 'various': 58,
 'e': 59,
 'commerce': 60,
 'websites': 61,
 'product': 62,
 'tracking': 63,
 'parcels': 64,
 'during': 65,
 'delivery': 66,
 'are': 67,
 'part': 68,
 'analytics': 69,
 'which': 70,
 'invo

In [35]:
for word, index in tokenizer.word_index.items():
  if index==pos:
    print(word)

plays


In [36]:
text3 = "Data plays a vital role"

# tokenization
token_text3 = tokenizer.texts_to_sequences([text3])[0]
# padding
padded_text3 = pad_sequences([token_text3], maxlen=33, padding='pre')
# model prediction
model.predict(padded_text3)

pos3 = np.argmax(model.predict(padded_text3))

for word, index in tokenizer.word_index.items():
  if index==pos3:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
in


In [37]:
text3 = "Data is a vital role in our everyday life"

# tokenization
token_text3 = tokenizer.texts_to_sequences([text3])[0]
# padding
padded_text3 = pad_sequences([token_text3], maxlen=33, padding='pre')
# model prediction
model.predict(padded_text3)

pos3 = np.argmax(model.predict(padded_text3))

for word, index in tokenizer.word_index.items():
  if index==pos3:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
life


#### **Improvements:**

1. Increasing the LSTM units
2. Increasing the Dense layers
3. Increasing the data
4. Using a pre-trained model on a larger corpus of data
5. Hyper parameter optimization